# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    kernelParams = [ "ip=dhcp" ]; 
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    initrd = {
      availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "tg3" "broadcom" ];
      kernelModules = [ "dm-snapshot" "cryptd" ]; # cryptd for LUKS support
      network = {
        enable = true;
        ssh = {
          enable = true;
          port = 22;
          authorizedKeys = [
            "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1e9dtSdX7Cv6+qWQk+FHQUkZw/6GH1PL4zwlJvjhEIZqMWVuXM48Gj42CInlm1Xz/Ygsf5F6jWOQEY+Ckav1ofRZ5bhAh7hB0zz3hLKBoFguVoCcGjuQgzzMI+REp34wcb4QqkF3bT9OfK5CTw0ud9nTzEkgQIDUV+MaQvrKT90iU6nT0357gZDCjuPyHaZ/ib5THNkHvef5sY5KBvw5HueGIC4kKa7k130Evw34vTM5ON9v/9iiY/bz2jiY46UwhdZ+V++BYpwsqFP3TqwEZXLLkfMfSiCLy4iVPg5otEAwDIw2fT7ek5itrOMAbgqZ62pY6W+IEsWXSM7Ce+gjzxG8li/1mjLwW0grHL/gipvz8S4z9wYqa3H1fNN4i4kVamq3cdIDQY01/xiEztmZawxkGAbJySR/OiduFiDVHkvUkfYi5ZSFh9IG8eWZGkntxtBVxYKljv1lXYA4/0oRRJaHfAyBMem7//S/xf24tcQ0yedMSjYnUL5uiWa0jB+k= openpgp:0xB028E14C"
          ];
          hostKeys = [ "/etc/secrets/initrd/ssh_host_rsa_key" ];
          shell = "/bin/cryptsetup-askpass";
        };
      };
    };
  };

  # Primary LUKS device
  boot.initrd.luks.devices."cryptdrive".device = "/dev/disk/by-uuid/83786a77-8ea3-4fb4-8214-edc3a5131f77";
  boot.initrd.luks.devices."cryptmedia".device = "/dev/disk/by-uuid/0c11273b-50d5-49c9-8b60-101a39f6da8e";
  boot.initrd.luks.devices."cryptdrive".preLVM = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d0cd8219-31c5-4375-bb6e-df3496a09d67";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7489-0336";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/260c1f0c-0e80-4daf-8782-8eaa63fdc705";
      fsType = "ext4";
    };

  fileSystems."/opt/services" =
    { device = "/dev/disk/by-uuid/5a58b7a3-25e0-4f8d-80be-421ab9379bb9";
      fsType = "ext4";
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/65f4763d-aa35-4d69-aa3e-95422676a09a";
      fsType = "ext4";
    };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/56824607-d371-41b8-bd9d-6832bf8ae848"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableAllFirmware = true; # Extended compability
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
